export const MAPS = {
  forest: {
    key: "forest",
    order: 1,
    name: "Ruinas del Bosque",
    description: "Terreno frondoso cruzado por ríos. Usa el bosque como cobertura.",
    bg: "#0a1006",
    w: 10,
    h: 10,
    grid: [
      "GGGFGGGGGG",
      "GGGFGGWWGG",
      "GGGGGGWWGG",
      "GFGGGGGGGG",
      "GFMMGGGGGG",
      "GGGMGGGFFG",
      "GGGGGGGFFG",
      "GGGGFGGGGG",
      "WWGGFGGGGG",
      "WWGGGGGGGG",
    ],
    playerSpawns: [
      { type: "warrior", row: 7, col: 1 },
      { type: "archer", row: 8, col: 2 },
      { type: "mage", row: 9, col: 3 },
    ],
    deployZone: [
      [6, 0], [6, 1], [6, 2],
      [7, 0], [7, 1], [7, 2], [7, 3],
      [8, 2], [8, 3],
      [9, 3], [9, 4],
    ],
    enemyDeployZone: [
      [0, 6], [0, 7], [0, 8], [0, 9],
      [1, 5], [1, 6],
      [2, 5], [2, 6],
      [3, 5], [3, 6], [3, 7], [3, 8], [3, 9],
      [4, 5], [4, 6],
    ],
    levels: [
      {
        level: 1,
        name: "Exploradores",
        enemySpawns: [
          { type: "goblin" },
          { type: "goblin" },
        ],
      },
      {
        level: 2,
        name: "Emboscada",
        enemySpawns: [
          { type: "goblin" },
          { type: "goblin" },
          { type: "orc" },
        ],
      },
      {
        level: 3,
        name: "Refuerzos",
        enemySpawns: [
          { type: "orc" },
          { type: "goblin" },
          { type: "darkmage" },
        ],
      },
      {
        level: 4,
        name: "Asedio",
        enemySpawns: [
          { type: "orc" },
          { type: "orc" },
          { type: "darkmage" },
        ],
      },
      {
        level: 5,
        isBoss: true,
        name: "El Señor del Bosque",
        enemySpawns: [
          { type: "orc", isBoss: true },
          { type: "goblin" },
          { type: "darkmage" },
          { type: "goblin" },
        ],
      },
    ],
  },

  desert: {
    key: "desert",
    order: 2,
    name: "Cañón del Desierto",
    description: "Pasajes estrechos entre montañas. La posición lo es todo.",
    bg: "#1a0e04",
    w: 10,
    h: 10,
    grid: [
      "SSSSMMSSSS",
      "SSSSMGMSSS",
      "SSMGGGGMSS",
      "SMGGGGGMSS",
      "MGGGGGGGMS",
      "MGGGGGGGMS",
      "SMGGGGGMSS",
      "SSMGGGGMSS",
      "SSSSMGMSSS",
      "SSSSMMSSSS",
    ],
    playerSpawns: [
      { type: "warrior", row: 5, col: 1 },
      { type: "archer", row: 4, col: 1 },
      { type: "mage", row: 6, col: 2 },
    ],
    deployZone: [
      [3, 1],
      [4, 1], [4, 2],
      [5, 1], [5, 2],
      [6, 1], [6, 2],
      [7, 2],
    ],
    enemyDeployZone: [
      [2, 6], [2, 7],
      [3, 6], [3, 7], [3, 8],
      [4, 6], [4, 7], [4, 8],
      [5, 6], [5, 7], [5, 8],
      [6, 6], [6, 7],
    ],
    levels: [
      {
        level: 1,
        name: "Centinelas",
        enemySpawns: [
          { type: "orc" },
          { type: "goblin" },
        ],
      },
      {
        level: 2,
        name: "Guardia del Cañón",
        enemySpawns: [
          { type: "orc" },
          { type: "orc" },
          { type: "goblin" },
        ],
      },
      {
        level: 3,
        name: "Hechiceros del Desierto",
        enemySpawns: [
          { type: "darkmage" },
          { type: "orc" },
          { type: "goblin" },
        ],
      },
      {
        level: 4,
        name: "Tormenta de Arena",
        enemySpawns: [
          { type: "darkmage" },
          { type: "darkmage" },
          { type: "orc" },
        ],
      },
      {
        level: 5,
        isBoss: true,
        name: "El Faraón Oscuro",
        enemySpawns: [
          { type: "darkmage", isBoss: true },
          { type: "orc" },
          { type: "orc" },
          { type: "goblin" },
        ],
      },
    ],
  },

  volcano: {
    key: "volcano",
    order: 3,
    name: "Lago de Lava",
    description: "Plataformas sobre magma. Mantén a tus unidades en tierra segura.",
    bg: "#140804",
    w: 10,
    h: 10,
    grid: [
      "VVVVIIGGVV",
      "VVVIWWGIVV",
      "VVIWWWWIVV",
      "VIGGWWGGIV",
      "IGGGGWGGGI",
      "IGGGGWGGGI",
      "VIGGWWGGIV",
      "VVIWWWWIVV",
      "VVVIWWGIVV",
      "VVVVIIGVVV",
    ],
    playerSpawns: [
      { type: "warrior", row: 4, col: 1 },
      { type: "archer", row: 5, col: 1 },
      { type: "mage", row: 4, col: 2 },
    ],
    deployZone: [
      [3, 1], [3, 2],
      [4, 1], [4, 2], [4, 3],
      [5, 1], [5, 2], [5, 3],
      [6, 1], [6, 2],
    ],
    enemyDeployZone: [
      [3, 7], [3, 8],
      [4, 6], [4, 7], [4, 8],
      [5, 6], [5, 7], [5, 8],
      [6, 7], [6, 8],
    ],
    levels: [
      {
        level: 1,
        name: "Guardianes de la Lava",
        enemySpawns: [
          { type: "orc" },
          { type: "goblin" },
        ],
      },
      {
        level: 2,
        name: "Demonios del Fuego",
        enemySpawns: [
          { type: "orc" },
          { type: "darkmage" },
          { type: "goblin" },
        ],
      },
      {
        level: 3,
        name: "Oleada Ardiente",
        enemySpawns: [
          { type: "orc" },
          { type: "orc" },
          { type: "darkmage" },
        ],
      },
      {
        level: 4,
        name: "Invocan las Llamas",
        enemySpawns: [
          { type: "darkmage" },
          { type: "darkmage" },
          { type: "orc" },
          { type: "goblin" },
        ],
      },
      {
        level: 5,
        isBoss: true,
        name: "El Señor del Volcán",
        enemySpawns: [
          { type: "darkmage", isBoss: true },
          { type: "orc" },
          { type: "darkmage" },
          { type: "orc" },
        ],
      },
    ],
  },
};