import { LAVA_TILE_DAMAGE } from "./constants";

export const TILE_TYPES = {
  G: {
    key: "G",
    name: "Pradera",
    walkable: true,
    moveCost: 1,
    bg: "#1e3210",
    decorUrl: null,
    effect: null,
  },
  F: {
    key: "F",
    name: "Bosque",
    walkable: true,
    moveCost: 2,
    bg: "#0f2008",
    decorUrl: null,
    effect: null,
  },
  M: {
    key: "M",
    name: "Montaña",
    walkable: false,
    moveCost: 0,
    bg: "#2e2a26",
    decorUrl: null,
    effect: null,
  },
  W: {
    key: "W",
    name: "Agua",
    walkable: false,
    moveCost: 0,
    bg: "#08203a",
    decorUrl: null,
    effect: null,
  },
  S: {
    key: "S",
    name: "Arena",
    walkable: true,
    moveCost: 1,
    bg: "#3c2e10",
    decorUrl: null,
    effect: null,
  },
  I: {
    key: "I",
    name: "Hielo",
    walkable: true,
    moveCost: 1,
    bg: "#14283c",
    decorUrl: null,
    effect: null,
  },
  V: {
    key: "V",
    name: "Lava",
    walkable: true,
    moveCost: 2,
    bg: "#3a1408",
    decorUrl: null,
    effect: { type: "damage", amount: LAVA_TILE_DAMAGE },
  },
};
